# 객실 비밀번호 설정
room_passwords:
  "102": "2012"
  "103": "3012"
  "104": "4012"
  "105": "5012"
  "201": "1021"
  "202": "2021"
  "203": "3021"
  "204": "4021"
  "205": "5021"
  "206": "6021"
  "207": "7021"

default_password: "0000"

# 객실별 체크인 안내 템플릿 매핑
room_template_mapping:
  "103": "check_in_guide_female_dorm"  # 여성 도미토리
  "205": "check_in_guide_male_dorm"    # 남성 도미토리
  default: "check_in_guide_normal"      # 일반 객실

# 객실 이름 매핑
room_names:
  "101": "트윈베드, 2인실"
  "102": "트윈베드, 2인실"
  "103": "여성 도미토리"
  "104": "더블사이즈, 1인실 단독"
  "105": "더블사이즈, 1인실 단독"
  "201": "성산일출봉뷰, 1인실 단독"
  "202": "트윈베드, 2인실"
  "203": "퀸사이즈, 1~2인 단독"
  "204": "트리플 룸, 최대 3인 단독"
  "205": "남성 도미토리"
  "206": "트윈베드, 2인실"
  "207": "트윈베드, 2인실"
