accommodation:
  name: "바움 게스트하우스"
  address: "제주특별자치도 서귀포시 성산읍 성산리 181-1"
  emergency_contact: "010-9436-3951"

wifi:
  ssid: "StayTuned_WiFi"
  password: "staytuned0131"

schedule:
  check_in_time: "15:00"
  check_out_time: "11:00"
room_passwords:
  "102": "2012"
  "103": "3012"
  "104": "4012"
  "105": "5012"

  "201": "1021"
  "202": "2021"
  "203": "3021"
  "204": "4021"
  "205": "5021"
  "206": "6021"
  "207": "7021"

default_password: "0000"
